// UI Localization Strings for all 22 languages
const UI_STRINGS = {
  en: {
    nav_home: "Home",
    nav_guide: "City Guides",
    nav_about: "About",
    nav_privacy: "Privacy",
    nav_terms: "Terms",
    nav_contact: "Contact",
    header_tagline: "Negotiate in any language. Tap a phrase, copy it, close the deal.",
    label_i_speak: "I speak",
    label_they_speak: "They speak",
    btn_buying: "🛒 I'm Buying",
    btn_selling: "💰 I'm Selling",
    cat_opening: "Opening & Greeting",
    cat_negotiating: "Negotiating Price",
    cat_logistics: "Logistics",
    cat_closing: "Closing the Deal",
    cat_listing: "Listing & Greeting",
    custom_placeholder: "Type your own phrase to translate...",
    btn_translate: "Translate →",
    toast_copied: "✅ Copied! Paste it in your chat",
    guide_cta: "📖 How to Negotiate on Facebook Marketplace →",
    guide_cta_sub: "Tips, etiquette, safety advice, and how to handle language barriers",
    footer_copyright: "© 2026 Haggly. Built with ❤️ for the global marketplace.",
    footer_about: "About",
    footer_privacy: "Privacy Policy",
    footer_terms: "Terms of Service",
    footer_contact: "Contact",
    custom_no_translation: "Custom translation requires an internet connection. For now, use the preset phrases above!",
    page_about_title: "About Haggly",
    page_about_subtitle: "Breaking language barriers in local commerce",
    page_guide_title: "How to Negotiate on Facebook Marketplace",
    page_guide_subtitle: "A complete guide to getting better deals, staying safe, and communicating across language barriers",
    page_privacy_title: "Privacy Policy",
    page_privacy_subtitle: "Last updated: February 14, 2026",
    page_terms_title: "Terms of Service",
    page_terms_subtitle: "Last updated: February 14, 2026",
    page_contact_title: "Contact Us",
    page_contact_subtitle: "Questions, feedback, or translation suggestions? We'd love to hear from you.",
    swap_title: "Swap languages",
    negotiation_tool: "💬 Negotiation Generator",
    nego_asking_price: "Asking Price",
    nego_target_price: "Your Target Price",
    nego_walkaway_price: "Your Walk-Away Price",
    nego_generate: "Generate Phrases ✨",
    nego_tone_friendly: "Friendly",
    nego_tone_savvy: "Savvy",
    nego_tone_walkaway: "Walk-Away",
    nav_phrases: "Phrases",
    browse_phrases_cta: "Browse All Phrases →",
    browse_phrases_sub: "Ready-made buyer and seller phrases in any language — tap, copy, paste",
    phrases_page_title: "Haggling Phrases",
    phrases_page_subtitle: "Browse, copy, and use negotiation phrases in any language.",
    generator_cta: "Try the Negotiation Generator →",
    generator_cta_sub: "Enter prices and get custom negotiation scripts in any language"
  },
  es: {
    nav_home: "Inicio",
    nav_guide: "Guías de Ciudades",
    nav_about: "Acerca de",
    nav_privacy: "Privacidad",
    nav_terms: "Términos",
    nav_contact: "Contacto",
    header_tagline: "Negocia en cualquier idioma. Toca una frase, cópiala, cierra el trato.",
    label_i_speak: "Yo hablo",
    label_they_speak: "Ellos hablan",
    btn_buying: "🛒 Estoy comprando",
    btn_selling: "💰 Estoy vendiendo",
    cat_opening: "Saludo e inicio",
    cat_negotiating: "Negociación de precio",
    cat_logistics: "Logística",
    cat_closing: "Cerrando el trato",
    cat_listing: "Publicación y saludo",
    custom_placeholder: "Escribe tu propia frase para traducir...",
    btn_translate: "Traducir →",
    toast_copied: "✅ ¡Copiado! Pégalo en tu chat",
    guide_cta: "📖 Cómo negociar en Facebook Marketplace →",
    guide_cta_sub: "Consejos, etiqueta, seguridad y cómo manejar barreras de idioma",
    footer_copyright: "© 2026 Haggly. Hecho con ❤️ para el mercado global.",
    footer_about: "Acerca de",
    footer_privacy: "Política de privacidad",
    footer_terms: "Términos de servicio",
    footer_contact: "Contacto",
    custom_no_translation: "La traducción personalizada requiere conexión a internet. ¡Por ahora, usa las frases predeterminadas!",
    page_about_title: "Acerca de Haggly",
    page_about_subtitle: "Rompiendo barreras de idioma en el comercio local",
    page_guide_title: "Cómo negociar en Facebook Marketplace",
    page_guide_subtitle: "Guía completa para conseguir mejores ofertas y comunicarse entre idiomas",
    page_privacy_title: "Política de privacidad",
    page_privacy_subtitle: "Última actualización: 14 de febrero de 2026",
    page_terms_title: "Términos de servicio",
    page_terms_subtitle: "Última actualización: 14 de febrero de 2026",
    page_contact_title: "Contáctanos",
    page_contact_subtitle: "¿Preguntas, comentarios o sugerencias de traducción? Nos encantaría saber de ti.",
    swap_title: "Intercambiar idiomas",
    negotiation_tool: "💬 Generador de Negociación",
    nego_asking_price: "Precio pedido",
    nego_target_price: "Tu precio objetivo",
    nego_walkaway_price: "Tu precio mínimo",
    nego_generate: "Generar frases ✨",
    nego_tone_friendly: "Amigable",
    nego_tone_savvy: "Astuto",
    nego_tone_walkaway: "Retirarse"
  },
  zh: {
    nav_home: "首页",
    nav_guide: "城市指南",
    nav_about: "关于",
    nav_privacy: "隐私",
    nav_terms: "条款",
    nav_contact: "联系",
    header_tagline: "用任何语言谈价。点击短语，复制，成交。",
    label_i_speak: "我说",
    label_they_speak: "对方说",
    btn_buying: "🛒 我要买",
    btn_selling: "💰 我要卖",
    cat_opening: "开场与问候",
    cat_negotiating: "价格谈判",
    cat_logistics: "物流安排",
    cat_closing: "完成交易",
    cat_listing: "发布与问候",
    custom_placeholder: "输入你自己的短语来翻译...",
    btn_translate: "翻译 →",
    toast_copied: "✅ 已复制！粘贴到你的聊天中",
    guide_cta: "📖 如何在Facebook Marketplace上谈价 →",
    guide_cta_sub: "技巧、礼仪、安全建议以及如何应对语言障碍",
    footer_copyright: "© 2026 Haggly。为全球市场用❤️打造。",
    footer_about: "关于",
    footer_privacy: "隐私政策",
    footer_terms: "服务条款",
    footer_contact: "联系我们",
    custom_no_translation: "自定义翻译需要网络连接。目前请使用上方的预设短语！",
    page_about_title: "关于 Haggly",
    page_about_subtitle: "消除本地商业中的语言障碍",
    page_guide_title: "如何在Facebook Marketplace上谈价",
    page_guide_subtitle: "获得更好交易和跨语言沟通的完整指南",
    page_privacy_title: "隐私政策",
    page_privacy_subtitle: "最后更新：2026年2月14日",
    page_terms_title: "服务条款",
    page_terms_subtitle: "最后更新：2026年2月14日",
    page_contact_title: "联系我们",
    page_contact_subtitle: "有问题、反馈或翻译建议？我们很乐意听取您的意见。",
    swap_title: "切换语言",
    negotiation_tool: "💬 谈判生成器",
    nego_asking_price: "要价",
    nego_target_price: "目标价格",
    nego_walkaway_price: "底线价格",
    nego_generate: "生成短语 ✨",
    nego_tone_friendly: "友好",
    nego_tone_savvy: "老练",
    nego_tone_walkaway: "走开"
  },
  ar: {
    nav_home: "الرئيسية",
    nav_guide: "أدلة المدن",
    nav_about: "من نحن",
    nav_privacy: "الخصوصية",
    nav_terms: "الشروط",
    nav_contact: "اتصل بنا",
    header_tagline: "تفاوض بأي لغة. انقر على عبارة، انسخها، أتمم الصفقة.",
    label_i_speak: "أتحدث",
    label_they_speak: "يتحدثون",
    btn_buying: "🛒 أنا أشتري",
    btn_selling: "💰 أنا أبيع",
    cat_opening: "الترحيب والبداية",
    cat_negotiating: "التفاوض على السعر",
    cat_logistics: "التنسيق والتسليم",
    cat_closing: "إتمام الصفقة",
    cat_listing: "الإعلان والترحيب",
    custom_placeholder: "اكتب عبارتك الخاصة للترجمة...",
    btn_translate: "ترجم →",
    toast_copied: "✅ تم النسخ! الصقه في محادثتك",
    guide_cta: "📖 كيف تتفاوض في Facebook Marketplace →",
    guide_cta_sub: "نصائح وآداب وسلامة وكيفية التعامل مع حواجز اللغة",
    footer_copyright: "© 2026 Haggly. صُنع بـ ❤️ للسوق العالمي.",
    footer_about: "من نحن",
    footer_privacy: "سياسة الخصوصية",
    footer_terms: "شروط الخدمة",
    footer_contact: "اتصل بنا",
    custom_no_translation: "الترجمة المخصصة تحتاج اتصال بالإنترنت. حاليًا، استخدم العبارات الجاهزة أعلاه!",
    page_about_title: "عن Haggly",
    page_about_subtitle: "كسر حواجز اللغة في التجارة المحلية",
    page_guide_title: "كيف تتفاوض في Facebook Marketplace",
    page_guide_subtitle: "دليل شامل للحصول على صفقات أفضل والتواصل عبر اللغات",
    page_privacy_title: "سياسة الخصوصية",
    page_privacy_subtitle: "آخر تحديث: 14 فبراير 2026",
    page_terms_title: "شروط الخدمة",
    page_terms_subtitle: "آخر تحديث: 14 فبراير 2026",
    page_contact_title: "اتصل بنا",
    page_contact_subtitle: "أسئلة أو ملاحظات أو اقتراحات ترجمة؟ يسعدنا سماعك.",
    swap_title: "تبديل اللغات",
    negotiation_tool: "💬 مولد التفاوض",
    nego_asking_price: "السعر المطلوب",
    nego_target_price: "السعر المستهدف",
    nego_walkaway_price: "أقل سعر مقبول",
    nego_generate: "إنشاء عبارات ✨",
    nego_tone_friendly: "ودود",
    nego_tone_savvy: "ذكي",
    nego_tone_walkaway: "الانسحاب"
  },
  hi: {
    nav_home: "होम",
    nav_guide: "शहर गाइड",
    nav_about: "हमारे बारे में",
    nav_privacy: "गोपनीयता",
    nav_terms: "शर्तें",
    nav_contact: "संपर्क",
    header_tagline: "किसी भी भाषा में मोलभाव करें। फ्रेज़ टैप करें, कॉपी करें, डील पक्की करें।",
    label_i_speak: "मैं बोलता हूँ",
    label_they_speak: "वे बोलते हैं",
    btn_buying: "🛒 मैं खरीद रहा हूँ",
    btn_selling: "💰 मैं बेच रहा हूँ",
    cat_opening: "शुरुआत और अभिवादन",
    cat_negotiating: "कीमत पर बातचीत",
    cat_logistics: "लॉजिस्टिक्स",
    cat_closing: "सौदा पक्का करना",
    cat_listing: "लिस्टिंग और अभिवादन",
    custom_placeholder: "अनुवाद के लिए अपना वाक्य लिखें...",
    btn_translate: "अनुवाद करें →",
    toast_copied: "✅ कॉपी हो गया! अपने चैट में पेस्ट करें",
    guide_cta: "📖 Facebook Marketplace पर कैसे मोलभाव करें →",
    guide_cta_sub: "टिप्स, शिष्टाचार, सुरक्षा सलाह और भाषा बाधाओं से निपटने के तरीके",
    footer_copyright: "© 2026 Haggly. वैश्विक बाज़ार के लिए ❤️ से बनाया गया।",
    footer_about: "हमारे बारे में",
    footer_privacy: "गोपनीयता नीति",
    footer_terms: "सेवा की शर्तें",
    footer_contact: "संपर्क करें",
    custom_no_translation: "कस्टम अनुवाद के लिए इंटरनेट कनेक्शन ज़रूरी है। अभी ऊपर दिए गए फ्रेज़ इस्तेमाल करें!",
    page_about_title: "Haggly के बारे में",
    page_about_subtitle: "स्थानीय व्यापार में भाषा की बाधाओं को तोड़ना",
    page_guide_title: "Facebook Marketplace पर कैसे मोलभाव करें",
    page_guide_subtitle: "बेहतर सौदे पाने और भाषाओं के पार संवाद करने की पूरी गाइड",
    page_privacy_title: "गोपनीयता नीति",
    page_privacy_subtitle: "अंतिम अपडेट: 14 फरवरी 2026",
    page_terms_title: "सेवा की शर्तें",
    page_terms_subtitle: "अंतिम अपडेट: 14 फरवरी 2026",
    page_contact_title: "संपर्क करें",
    page_contact_subtitle: "सवाल, फीडबैक या अनुवाद सुझाव? हम आपसे सुनना चाहेंगे।",
    swap_title: "भाषाएँ बदलें",
    negotiation_tool: "💬 मोलभाव जनरेटर",
    nego_asking_price: "मांगा गया दाम",
    nego_target_price: "आपका लक्ष्य दाम",
    nego_walkaway_price: "आपका न्यूनतम दाम",
    nego_generate: "वाक्य बनाएं ✨",
    nego_tone_friendly: "मैत्रीपूर्ण",
    nego_tone_savvy: "चतुर",
    nego_tone_walkaway: "चले जाओ"
  },
  pt: {
    nav_home: "Início",
    nav_guide: "Guias de Cidades",
    nav_about: "Sobre",
    nav_privacy: "Privacidade",
    nav_terms: "Termos",
    nav_contact: "Contato",
    header_tagline: "Negocie em qualquer idioma. Toque em uma frase, copie, feche o negócio.",
    label_i_speak: "Eu falo",
    label_they_speak: "Eles falam",
    btn_buying: "🛒 Estou comprando",
    btn_selling: "💰 Estou vendendo",
    cat_opening: "Abertura e saudação",
    cat_negotiating: "Negociando preço",
    cat_logistics: "Logística",
    cat_closing: "Fechando o negócio",
    cat_listing: "Anúncio e saudação",
    custom_placeholder: "Digite sua frase para traduzir...",
    btn_translate: "Traduzir →",
    toast_copied: "✅ Copiado! Cole no seu chat",
    guide_cta: "📖 Como negociar no Facebook Marketplace →",
    guide_cta_sub: "Dicas, etiqueta, segurança e como lidar com barreiras de idioma",
    footer_copyright: "© 2026 Haggly. Feito com ❤️ para o mercado global.",
    footer_about: "Sobre",
    footer_privacy: "Política de privacidade",
    footer_terms: "Termos de serviço",
    footer_contact: "Contato",
    custom_no_translation: "Tradução personalizada requer conexão com a internet. Por enquanto, use as frases prontas acima!",
    page_about_title: "Sobre o Haggly",
    page_about_subtitle: "Quebrando barreiras de idioma no comércio local",
    page_guide_title: "Como negociar no Facebook Marketplace",
    page_guide_subtitle: "Guia completo para melhores negócios e comunicação entre idiomas",
    page_privacy_title: "Política de privacidade",
    page_privacy_subtitle: "Última atualização: 14 de fevereiro de 2026",
    page_terms_title: "Termos de serviço",
    page_terms_subtitle: "Última atualização: 14 de fevereiro de 2026",
    page_contact_title: "Fale conosco",
    page_contact_subtitle: "Dúvidas, feedback ou sugestões de tradução? Adoraríamos ouvir de você.",
    swap_title: "Trocar idiomas",
    negotiation_tool: "💬 Gerador de Negociação",
    nego_asking_price: "Preço pedido",
    nego_target_price: "Seu preço alvo",
    nego_walkaway_price: "Seu preço mínimo",
    nego_generate: "Gerar frases ✨",
    nego_tone_friendly: "Amigável",
    nego_tone_savvy: "Esperto",
    nego_tone_walkaway: "Desistir"
  },
  fr: {
    nav_home: "Accueil",
    nav_guide: "City Guides",
    nav_about: "À propos",
    nav_privacy: "Confidentialité",
    nav_terms: "Conditions",
    nav_contact: "Contact",
    header_tagline: "Négociez dans n'importe quelle langue. Touchez une phrase, copiez-la, concluez l'affaire.",
    label_i_speak: "Je parle",
    label_they_speak: "Ils parlent",
    btn_buying: "🛒 J'achète",
    btn_selling: "💰 Je vends",
    cat_opening: "Salutation et ouverture",
    cat_negotiating: "Négociation du prix",
    cat_logistics: "Logistique",
    cat_closing: "Conclure l'affaire",
    cat_listing: "Annonce et salutation",
    custom_placeholder: "Tapez votre propre phrase à traduire...",
    btn_translate: "Traduire →",
    toast_copied: "✅ Copié ! Collez-le dans votre conversation",
    guide_cta: "📖 Comment négocier sur Facebook Marketplace →",
    guide_cta_sub: "Conseils, étiquette, sécurité et gestion des barrières linguistiques",
    footer_copyright: "© 2026 Haggly. Fait avec ❤️ pour le marché mondial.",
    footer_about: "À propos",
    footer_privacy: "Politique de confidentialité",
    footer_terms: "Conditions d'utilisation",
    footer_contact: "Contact",
    custom_no_translation: "La traduction personnalisée nécessite une connexion internet. Utilisez les phrases prédéfinies ci-dessus !",
    page_about_title: "À propos de Haggly",
    page_about_subtitle: "Briser les barrières linguistiques dans le commerce local",
    page_guide_title: "Comment négocier sur Facebook Marketplace",
    page_guide_subtitle: "Guide complet pour de meilleures affaires et la communication entre langues",
    page_privacy_title: "Politique de confidentialité",
    page_privacy_subtitle: "Dernière mise à jour : 14 février 2026",
    page_terms_title: "Conditions d'utilisation",
    page_terms_subtitle: "Dernière mise à jour : 14 février 2026",
    page_contact_title: "Nous contacter",
    page_contact_subtitle: "Questions, commentaires ou suggestions de traduction ? On vous écoute.",
    swap_title: "Inverser les langues",
    negotiation_tool: "💬 Générateur de Négociation",
    nego_asking_price: "Prix demandé",
    nego_target_price: "Votre prix cible",
    nego_walkaway_price: "Votre prix minimum",
    nego_generate: "Générer des phrases ✨",
    nego_tone_friendly: "Amical",
    nego_tone_savvy: "Malin",
    nego_tone_walkaway: "Se retirer"
  },
  de: {
    nav_home: "Startseite",
    nav_guide: "Stadtführer",
    nav_about: "Über uns",
    nav_privacy: "Datenschutz",
    nav_terms: "AGB",
    nav_contact: "Kontakt",
    header_tagline: "Verhandeln Sie in jeder Sprache. Phrase antippen, kopieren, Deal abschließen.",
    label_i_speak: "Ich spreche",
    label_they_speak: "Die sprechen",
    btn_buying: "🛒 Ich kaufe",
    btn_selling: "💰 Ich verkaufe",
    cat_opening: "Begrüßung & Eröffnung",
    cat_negotiating: "Preisverhandlung",
    cat_logistics: "Logistik",
    cat_closing: "Geschäft abschließen",
    cat_listing: "Inserat & Begrüßung",
    custom_placeholder: "Geben Sie Ihre eigene Phrase ein...",
    btn_translate: "Übersetzen →",
    toast_copied: "✅ Kopiert! In den Chat einfügen",
    guide_cta: "📖 So verhandeln Sie auf Facebook Marketplace →",
    guide_cta_sub: "Tipps, Etikette, Sicherheit und Umgang mit Sprachbarrieren",
    footer_copyright: "© 2026 Haggly. Mit ❤️ für den globalen Marktplatz gebaut.",
    footer_about: "Über uns",
    footer_privacy: "Datenschutzrichtlinie",
    footer_terms: "Nutzungsbedingungen",
    footer_contact: "Kontakt",
    custom_no_translation: "Benutzerdefinierte Übersetzung erfordert Internetverbindung. Nutzen Sie vorerst die voreingestellten Phrasen!",
    page_about_title: "Über Haggly",
    page_about_subtitle: "Sprachbarrieren im lokalen Handel überwinden",
    page_guide_title: "So verhandeln Sie auf Facebook Marketplace",
    page_guide_subtitle: "Vollständiger Leitfaden für bessere Deals und Kommunikation über Sprachen hinweg",
    page_privacy_title: "Datenschutzrichtlinie",
    page_privacy_subtitle: "Zuletzt aktualisiert: 14. Februar 2026",
    page_terms_title: "Nutzungsbedingungen",
    page_terms_subtitle: "Zuletzt aktualisiert: 14. Februar 2026",
    page_contact_title: "Kontakt",
    page_contact_subtitle: "Fragen, Feedback oder Übersetzungsvorschläge? Wir freuen uns von Ihnen zu hören.",
    swap_title: "Sprachen tauschen",
    negotiation_tool: "💬 Verhandlungsgenerator",
    nego_asking_price: "Angebotspreis",
    nego_target_price: "Ihr Zielpreis",
    nego_walkaway_price: "Ihr Mindestpreis",
    nego_generate: "Phrasen generieren ✨",
    nego_tone_friendly: "Freundlich",
    nego_tone_savvy: "Clever",
    nego_tone_walkaway: "Weggehen"
  },
  ja: {
    nav_home: "ホーム",
    nav_guide: "都市ガイド",
    nav_about: "概要",
    nav_privacy: "プライバシー",
    nav_terms: "利用規約",
    nav_contact: "お問い合わせ",
    header_tagline: "どんな言語でも交渉できます。フレーズをタップ、コピー、取引成立。",
    label_i_speak: "私の言語",
    label_they_speak: "相手の言語",
    btn_buying: "🛒 買いたい",
    btn_selling: "💰 売りたい",
    cat_opening: "挨拶・はじめに",
    cat_negotiating: "値段交渉",
    cat_logistics: "受け渡し",
    cat_closing: "取引完了",
    cat_listing: "出品・挨拶",
    custom_placeholder: "翻訳したいフレーズを入力...",
    btn_translate: "翻訳 →",
    toast_copied: "✅ コピーしました！チャットに貼り付けてください",
    guide_cta: "📖 Facebook Marketplaceでの交渉方法 →",
    guide_cta_sub: "コツ、マナー、安全対策、言語の壁への対処法",
    footer_copyright: "© 2026 Haggly。グローバル市場のために❤️を込めて作りました。",
    footer_about: "概要",
    footer_privacy: "プライバシーポリシー",
    footer_terms: "利用規約",
    footer_contact: "お問い合わせ",
    custom_no_translation: "カスタム翻訳にはインターネット接続が必要です。今のところプリセットフレーズをお使いください！",
    page_about_title: "Hagglyについて",
    page_about_subtitle: "地域商取引の言語の壁を取り除く",
    page_guide_title: "Facebook Marketplaceでの交渉方法",
    page_guide_subtitle: "より良い取引と異言語コミュニケーションの完全ガイド",
    page_privacy_title: "プライバシーポリシー",
    page_privacy_subtitle: "最終更新日：2026年2月14日",
    page_terms_title: "利用規約",
    page_terms_subtitle: "最終更新日：2026年2月14日",
    page_contact_title: "お問い合わせ",
    page_contact_subtitle: "ご質問、フィードバック、翻訳の提案はこちらから。",
    swap_title: "言語を入れ替え",
    negotiation_tool: "💬 交渉フレーズ生成",
    nego_asking_price: "提示価格",
    nego_target_price: "目標価格",
    nego_walkaway_price: "最低価格",
    nego_generate: "フレーズ生成 ✨",
    nego_tone_friendly: "フレンドリー",
    nego_tone_savvy: "交渉上手",
    nego_tone_walkaway: "立ち去り"
  },
  ko: {
    nav_home: "홈",
    nav_guide: "도시 가이드",
    nav_about: "소개",
    nav_privacy: "개인정보",
    nav_terms: "이용약관",
    nav_contact: "연락처",
    header_tagline: "어떤 언어로든 협상하세요. 문구를 탭하고, 복사하고, 거래를 마무리하세요.",
    label_i_speak: "나의 언어",
    label_they_speak: "상대방 언어",
    btn_buying: "🛒 구매 중",
    btn_selling: "💰 판매 중",
    cat_opening: "인사 & 시작",
    cat_negotiating: "가격 협상",
    cat_logistics: "거래 방법",
    cat_closing: "거래 완료",
    cat_listing: "등록 & 인사",
    custom_placeholder: "번역할 문구를 입력하세요...",
    btn_translate: "번역 →",
    toast_copied: "✅ 복사됨! 채팅에 붙여넣기하세요",
    guide_cta: "📖 Facebook Marketplace 협상 방법 →",
    guide_cta_sub: "팁, 에티켓, 안전 조언, 언어 장벽 극복법",
    footer_copyright: "© 2026 Haggly. 글로벌 마켓플레이스를 위해 ❤️로 만들었습니다.",
    footer_about: "소개",
    footer_privacy: "개인정보 처리방침",
    footer_terms: "이용약관",
    footer_contact: "연락처",
    custom_no_translation: "사용자 정의 번역에는 인터넷 연결이 필요합니다. 지금은 위의 기본 문구를 사용하세요!",
    page_about_title: "Haggly 소개",
    page_about_subtitle: "지역 상거래의 언어 장벽을 허물다",
    page_guide_title: "Facebook Marketplace 협상 방법",
    page_guide_subtitle: "더 나은 거래와 다국어 소통을 위한 완전한 가이드",
    page_privacy_title: "개인정보 처리방침",
    page_privacy_subtitle: "마지막 업데이트: 2026년 2월 14일",
    page_terms_title: "이용약관",
    page_terms_subtitle: "마지막 업데이트: 2026년 2월 14일",
    page_contact_title: "문의하기",
    page_contact_subtitle: "질문, 피드백 또는 번역 제안이 있으신가요?",
    swap_title: "언어 교환",
    negotiation_tool: "💬 협상 문구 생성기",
    nego_asking_price: "제시 가격",
    nego_target_price: "목표 가격",
    nego_walkaway_price: "최저 가격",
    nego_generate: "문구 생성 ✨",
    nego_tone_friendly: "친근한",
    nego_tone_savvy: "능숙한",
    nego_tone_walkaway: "떠나기"
  },
  vi: {
    nav_home: "Trang chủ",
    nav_guide: "Hướng dẫn Thành phố",
    nav_about: "Giới thiệu",
    nav_privacy: "Quyền riêng tư",
    nav_terms: "Điều khoản",
    nav_contact: "Liên hệ",
    header_tagline: "Thương lượng bằng bất kỳ ngôn ngữ nào. Chạm cụm từ, sao chép, chốt giao dịch.",
    label_i_speak: "Tôi nói",
    label_they_speak: "Họ nói",
    btn_buying: "🛒 Tôi mua",
    btn_selling: "💰 Tôi bán",
    cat_opening: "Chào hỏi & mở đầu",
    cat_negotiating: "Thương lượng giá",
    cat_logistics: "Hậu cần",
    cat_closing: "Chốt giao dịch",
    cat_listing: "Đăng bán & chào hỏi",
    custom_placeholder: "Nhập cụm từ bạn muốn dịch...",
    btn_translate: "Dịch →",
    toast_copied: "✅ Đã sao chép! Dán vào cuộc trò chuyện",
    guide_cta: "📖 Cách thương lượng trên Facebook Marketplace →",
    guide_cta_sub: "Mẹo, lịch sự, an toàn và cách xử lý rào cản ngôn ngữ",
    footer_copyright: "© 2026 Haggly. Được tạo với ❤️ cho thị trường toàn cầu.",
    footer_about: "Giới thiệu",
    footer_privacy: "Chính sách quyền riêng tư",
    footer_terms: "Điều khoản dịch vụ",
    footer_contact: "Liên hệ",
    custom_no_translation: "Dịch tùy chỉnh cần kết nối internet. Hãy dùng các cụm từ có sẵn ở trên!",
    page_about_title: "Về Haggly",
    page_about_subtitle: "Phá bỏ rào cản ngôn ngữ trong thương mại địa phương",
    page_guide_title: "Cách thương lượng trên Facebook Marketplace",
    page_guide_subtitle: "Hướng dẫn đầy đủ để có giao dịch tốt hơn và giao tiếp đa ngôn ngữ",
    page_privacy_title: "Chính sách quyền riêng tư",
    page_privacy_subtitle: "Cập nhật lần cuối: 14 tháng 2, 2026",
    page_terms_title: "Điều khoản dịch vụ",
    page_terms_subtitle: "Cập nhật lần cuối: 14 tháng 2, 2026",
    page_contact_title: "Liên hệ chúng tôi",
    page_contact_subtitle: "Câu hỏi, phản hồi hoặc đề xuất dịch thuật? Chúng tôi rất muốn nghe từ bạn.",
    swap_title: "Đổi ngôn ngữ",
    negotiation_tool: "💬 Tạo câu thương lượng",
    nego_asking_price: "Giá đề nghị",
    nego_target_price: "Giá mục tiêu",
    nego_walkaway_price: "Giá tối thiểu",
    nego_generate: "Tạo câu ✨",
    nego_tone_friendly: "Thân thiện",
    nego_tone_savvy: "Khéo léo",
    nego_tone_walkaway: "Bỏ đi"
  },
  tl: {
    nav_home: "Home",
    nav_guide: "Mga Gabay sa Lungsod",
    nav_about: "Tungkol",
    nav_privacy: "Privacy",
    nav_terms: "Tuntunin",
    nav_contact: "Kontak",
    header_tagline: "Makipag-negotiate sa kahit anong wika. I-tap ang phrase, kopyahin, isara ang deal.",
    label_i_speak: "Nagsasalita ako ng",
    label_they_speak: "Nagsasalita sila ng",
    btn_buying: "🛒 Bibili ako",
    btn_selling: "💰 Nagbebenta ako",
    cat_opening: "Pagbati at pagbubukas",
    cat_negotiating: "Pagnenegosyo ng presyo",
    cat_logistics: "Logistics",
    cat_closing: "Pagsasara ng deal",
    cat_listing: "Pag-list at pagbati",
    custom_placeholder: "I-type ang sarili mong phrase para i-translate...",
    btn_translate: "I-translate →",
    toast_copied: "✅ Nakopya! I-paste sa iyong chat",
    guide_cta: "📖 Paano Mag-negotiate sa Facebook Marketplace →",
    guide_cta_sub: "Tips, etiquette, safety advice, at paano harapin ang language barriers",
    footer_copyright: "© 2026 Haggly. Ginawa nang may ❤️ para sa global marketplace.",
    footer_about: "Tungkol",
    footer_privacy: "Patakaran sa Privacy",
    footer_terms: "Mga Tuntunin ng Serbisyo",
    footer_contact: "Kontak",
    custom_no_translation: "Kailangan ng internet connection para sa custom translation. Gamitin muna ang mga preset phrases sa itaas!",
    page_about_title: "Tungkol sa Haggly",
    page_about_subtitle: "Binubuwal ang mga hadlang sa wika sa lokal na kalakalan",
    page_guide_title: "Paano Mag-negotiate sa Facebook Marketplace",
    page_guide_subtitle: "Kumpletong gabay para sa mas magandang deals at komunikasyon sa iba't ibang wika",
    page_privacy_title: "Patakaran sa Privacy",
    page_privacy_subtitle: "Huling na-update: Pebrero 14, 2026",
    page_terms_title: "Mga Tuntunin ng Serbisyo",
    page_terms_subtitle: "Huling na-update: Pebrero 14, 2026",
    page_contact_title: "Kontakin Kami",
    page_contact_subtitle: "May tanong, feedback, o translation suggestion? Gusto naming marinig ang sayo.",
    swap_title: "Palitan ang mga wika",
    negotiation_tool: "💬 Tagabuo ng Negosasyon",
    nego_asking_price: "Presyong hinihingi",
    nego_target_price: "Target na presyo",
    nego_walkaway_price: "Pinakamababang presyo",
    nego_generate: "Gumawa ng mga parirala ✨",
    nego_tone_friendly: "Magiliw",
    nego_tone_savvy: "Matalino",
    nego_tone_walkaway: "Umalis"
  },
  ru: {
    nav_home: "Главная",
    nav_guide: "Гиды по городам",
    nav_about: "О нас",
    nav_privacy: "Конфиденциальность",
    nav_terms: "Условия",
    nav_contact: "Контакты",
    header_tagline: "Торгуйтесь на любом языке. Нажмите на фразу, скопируйте, заключите сделку.",
    label_i_speak: "Я говорю на",
    label_they_speak: "Они говорят на",
    btn_buying: "🛒 Покупаю",
    btn_selling: "💰 Продаю",
    cat_opening: "Приветствие",
    cat_negotiating: "Торг по цене",
    cat_logistics: "Логистика",
    cat_closing: "Заключение сделки",
    cat_listing: "Объявление и приветствие",
    custom_placeholder: "Введите свою фразу для перевода...",
    btn_translate: "Перевести →",
    toast_copied: "✅ Скопировано! Вставьте в чат",
    guide_cta: "📖 Как торговаться на Facebook Marketplace →",
    guide_cta_sub: "Советы, этикет, безопасность и языковые барьеры",
    footer_copyright: "© 2026 Haggly. Создано с ❤️ для мирового рынка.",
    footer_about: "О нас",
    footer_privacy: "Политика конфиденциальности",
    footer_terms: "Условия использования",
    footer_contact: "Контакты",
    custom_no_translation: "Для пользовательского перевода нужен интернет. Пока используйте готовые фразы выше!",
    page_about_title: "О Haggly",
    page_about_subtitle: "Ломаем языковые барьеры в местной торговле",
    page_guide_title: "Как торговаться на Facebook Marketplace",
    page_guide_subtitle: "Полное руководство по выгодным сделкам и общению на разных языках",
    page_privacy_title: "Политика конфиденциальности",
    page_privacy_subtitle: "Последнее обновление: 14 февраля 2026",
    page_terms_title: "Условия использования",
    page_terms_subtitle: "Последнее обновление: 14 февраля 2026",
    page_contact_title: "Свяжитесь с нами",
    page_contact_subtitle: "Вопросы, отзывы или предложения по переводу? Мы будем рады вас услышать.",
    swap_title: "Поменять языки",
    negotiation_tool: "💬 Генератор фраз для торга",
    nego_asking_price: "Запрашиваемая цена",
    nego_target_price: "Ваша целевая цена",
    nego_walkaway_price: "Ваша минимальная цена",
    nego_generate: "Создать фразы ✨",
    nego_tone_friendly: "Дружелюбный",
    nego_tone_savvy: "Опытный",
    nego_tone_walkaway: "Уход"
  },
  pl: {
    nav_home: "Strona główna",
    nav_guide: "Przewodniki miejskie",
    nav_about: "O nas",
    nav_privacy: "Prywatność",
    nav_terms: "Regulamin",
    nav_contact: "Kontakt",
    header_tagline: "Negocjuj w dowolnym języku. Kliknij frazę, skopiuj, zamknij deal.",
    label_i_speak: "Mówię po",
    label_they_speak: "Oni mówią po",
    btn_buying: "🛒 Kupuję",
    btn_selling: "💰 Sprzedaję",
    cat_opening: "Powitanie i otwarcie",
    cat_negotiating: "Negocjacja ceny",
    cat_logistics: "Logistyka",
    cat_closing: "Zamknięcie transakcji",
    cat_listing: "Ogłoszenie i powitanie",
    custom_placeholder: "Wpisz własną frazę do przetłumaczenia...",
    btn_translate: "Tłumacz →",
    toast_copied: "✅ Skopiowano! Wklej w czacie",
    guide_cta: "📖 Jak negocjować na Facebook Marketplace →",
    guide_cta_sub: "Wskazówki, etykieta, bezpieczeństwo i bariery językowe",
    footer_copyright: "© 2026 Haggly. Zbudowane z ❤️ dla globalnego rynku.",
    footer_about: "O nas",
    footer_privacy: "Polityka prywatności",
    footer_terms: "Regulamin",
    footer_contact: "Kontakt",
    custom_no_translation: "Tłumaczenie niestandardowe wymaga połączenia z internetem. Na razie użyj gotowych fraz powyżej!",
    page_about_title: "O Haggly",
    page_about_subtitle: "Przełamujemy bariery językowe w lokalnym handlu",
    page_guide_title: "Jak negocjować na Facebook Marketplace",
    page_guide_subtitle: "Kompletny poradnik lepszych transakcji i komunikacji między językami",
    page_privacy_title: "Polityka prywatności",
    page_privacy_subtitle: "Ostatnia aktualizacja: 14 lutego 2026",
    page_terms_title: "Regulamin",
    page_terms_subtitle: "Ostatnia aktualizacja: 14 lutego 2026",
    page_contact_title: "Kontakt",
    page_contact_subtitle: "Pytania, opinie lub sugestie tłumaczeń? Chętnie wysłuchamy.",
    swap_title: "Zamień języki",
    negotiation_tool: "💬 Generator negocjacji",
    nego_asking_price: "Cena wywoławcza",
    nego_target_price: "Twoja cena docelowa",
    nego_walkaway_price: "Twoja cena minimalna",
    nego_generate: "Generuj frazy ✨",
    nego_tone_friendly: "Przyjazny",
    nego_tone_savvy: "Sprytny",
    nego_tone_walkaway: "Odejście"
  },
  uk: {
    nav_home: "Головна",
    nav_guide: "Міські гіди",
    nav_about: "Про нас",
    nav_privacy: "Конфіденційність",
    nav_terms: "Умови",
    nav_contact: "Контакти",
    header_tagline: "Торгуйтеся будь-якою мовою. Натисніть фразу, скопіюйте, укладіть угоду.",
    label_i_speak: "Я розмовляю",
    label_they_speak: "Вони розмовляють",
    btn_buying: "🛒 Купую",
    btn_selling: "💰 Продаю",
    cat_opening: "Привітання та початок",
    cat_negotiating: "Торг за ціною",
    cat_logistics: "Логістика",
    cat_closing: "Укладення угоди",
    cat_listing: "Оголошення та привітання",
    custom_placeholder: "Введіть свою фразу для перекладу...",
    btn_translate: "Перекласти →",
    toast_copied: "✅ Скопійовано! Вставте в чат",
    guide_cta: "📖 Як торгуватися на Facebook Marketplace →",
    guide_cta_sub: "Поради, етикет, безпека та подолання мовних бар'єрів",
    footer_copyright: "© 2026 Haggly. Створено з ❤️ для глобального ринку.",
    footer_about: "Про нас",
    footer_privacy: "Політика конфіденційності",
    footer_terms: "Умови використання",
    footer_contact: "Контакти",
    custom_no_translation: "Користувацький переклад потребує інтернету. Поки що використовуйте готові фрази вище!",
    page_about_title: "Про Haggly",
    page_about_subtitle: "Руйнуємо мовні бар'єри в місцевій торгівлі",
    page_guide_title: "Як торгуватися на Facebook Marketplace",
    page_guide_subtitle: "Повний посібник з вигідних угод та спілкування різними мовами",
    page_privacy_title: "Політика конфіденційності",
    page_privacy_subtitle: "Останнє оновлення: 14 лютого 2026",
    page_terms_title: "Умови використання",
    page_terms_subtitle: "Останнє оновлення: 14 лютого 2026",
    page_contact_title: "Зв'яжіться з нами",
    page_contact_subtitle: "Запитання, відгуки чи пропозиції перекладу? Ми раді вас вислухати.",
    swap_title: "Поміняти мови",
    negotiation_tool: "💬 Генератор фраз для торгу",
    nego_asking_price: "Запитувана ціна",
    nego_target_price: "Ваша цільова ціна",
    nego_walkaway_price: "Ваша мінімальна ціна",
    nego_generate: "Створити фрази ✨",
    nego_tone_friendly: "Дружній",
    nego_tone_savvy: "Досвідчений",
    nego_tone_walkaway: "Відхід"
  },
  sw: {
    nav_home: "Nyumbani",
    nav_guide: "Miongozo ya Miji",
    nav_about: "Kuhusu",
    nav_privacy: "Faragha",
    nav_terms: "Masharti",
    nav_contact: "Wasiliana",
    header_tagline: "Jadiliana kwa lugha yoyote. Gusa sentensi, nakili, funga dili.",
    label_i_speak: "Ninazungumza",
    label_they_speak: "Wanazungumza",
    btn_buying: "🛒 Ninanunua",
    btn_selling: "💰 Ninauza",
    cat_opening: "Salamu na utangulizi",
    cat_negotiating: "Kujadili bei",
    cat_logistics: "Usafiri na mkutano",
    cat_closing: "Kufunga dili",
    cat_listing: "Tangazo na salamu",
    custom_placeholder: "Andika sentensi yako ya kutafsiri...",
    btn_translate: "Tafsiri →",
    toast_copied: "✅ Imenakiliwa! Bandika katika mazungumzo yako",
    guide_cta: "📖 Jinsi ya Kujadiliana kwenye Facebook Marketplace →",
    guide_cta_sub: "Vidokezo, adabu, usalama na jinsi ya kushughulikia vizuizi vya lugha",
    footer_copyright: "© 2026 Haggly. Imejengwa kwa ❤️ kwa soko la kimataifa.",
    footer_about: "Kuhusu",
    footer_privacy: "Sera ya Faragha",
    footer_terms: "Masharti ya Huduma",
    footer_contact: "Wasiliana",
    custom_no_translation: "Tafsiri maalum inahitaji muunganisho wa mtandao. Kwa sasa, tumia sentensi zilizo tayari hapo juu!",
    page_about_title: "Kuhusu Haggly",
    page_about_subtitle: "Kuvunja vizuizi vya lugha katika biashara ya ndani",
    page_guide_title: "Jinsi ya Kujadiliana kwenye Facebook Marketplace",
    page_guide_subtitle: "Mwongozo kamili wa dili bora na mawasiliano kati ya lugha",
    page_privacy_title: "Sera ya Faragha",
    page_privacy_subtitle: "Imesasishwa mwisho: Februari 14, 2026",
    page_terms_title: "Masharti ya Huduma",
    page_terms_subtitle: "Imesasishwa mwisho: Februari 14, 2026",
    page_contact_title: "Wasiliana Nasi",
    page_contact_subtitle: "Maswali, maoni au mapendekezo ya tafsiri? Tungependa kusikia kutoka kwako.",
    swap_title: "Badilisha lugha",
    negotiation_tool: "💬 Kizazi cha Mazungumzo",
    nego_asking_price: "Bei inayoombwa",
    nego_target_price: "Bei yako lengwa",
    nego_walkaway_price: "Bei yako ya chini",
    nego_generate: "Tengeneza sentensi ✨",
    nego_tone_friendly: "Kirafiki",
    nego_tone_savvy: "Mjuzi",
    nego_tone_walkaway: "Kuondoka"
  },
  ha: {
    nav_home: "Gida",
    nav_guide: "Jagororin Birane",
    nav_about: "Game da mu",
    nav_privacy: "Sirri",
    nav_terms: "Sharudda",
    nav_contact: "Tuntuɓe mu",
    header_tagline: "Yi ciniki da kowane yare. Danna jimla, kwafa, kammala ciniki.",
    label_i_speak: "Ina magana",
    label_they_speak: "Suna magana",
    btn_buying: "🛒 Ina saye",
    btn_selling: "💰 Ina sayarwa",
    cat_opening: "Gaisuwa da farawa",
    cat_negotiating: "Cinikayya kan farashi",
    cat_logistics: "Tsarin jigilar kaya",
    cat_closing: "Kammalawa ciniki",
    cat_listing: "Tallar da gaisuwa",
    custom_placeholder: "Rubuta jimlar ka don fassara...",
    btn_translate: "Fassara →",
    toast_copied: "✅ An kwafa! Manna a cikin tattaunawa",
    guide_cta: "📖 Yadda Ake Cinikayya a Facebook Marketplace →",
    guide_cta_sub: "Nasihu, ladabi, aminci da yadda ake magance matsalar harshe",
    footer_copyright: "© 2026 Haggly. An gina da ❤️ don kasuwar duniya.",
    footer_about: "Game da mu",
    footer_privacy: "Manufar Sirri",
    footer_terms: "Sharuddan Sabis",
    footer_contact: "Tuntuɓe mu",
    custom_no_translation: "Fassarar da kanka tana buƙatar haɗin yanar gizo. Yanzu, yi amfani da jimlolin da ke sama!",
    page_about_title: "Game da Haggly",
    page_about_subtitle: "Rushe shingen harshe a cikin kasuwancin gida",
    page_guide_title: "Yadda Ake Cinikayya a Facebook Marketplace",
    page_guide_subtitle: "Cikakken jagora don mafi kyawun cinikayya da sadarwa tsakanin harsuna",
    page_privacy_title: "Manufar Sirri",
    page_privacy_subtitle: "An sabunta karshe: Fabrairu 14, 2026",
    page_terms_title: "Sharuddan Sabis",
    page_terms_subtitle: "An sabunta karshe: Fabrairu 14, 2026",
    page_contact_title: "Tuntuɓe Mu",
    page_contact_subtitle: "Tambayoyi, ra'ayoyi ko shawarwarin fassara? Muna son jin daga gare ka.",
    swap_title: "Sauya harsuna",
    negotiation_tool: "💬 Mai Ƙirƙirar Cinikayya",
    nego_asking_price: "Farashin da ake nema",
    nego_target_price: "Farashin ka",
    nego_walkaway_price: "Ƙaramin farashi",
    nego_generate: "Ƙirƙiri jimloli ✨",
    nego_tone_friendly: "Mai kyau",
    nego_tone_savvy: "Gwani",
    nego_tone_walkaway: "Tafiya"
  },
  am: {
    nav_home: "መነሻ",
    nav_guide: "የከተማ መመሪያዎች",
    nav_about: "ስለ እኛ",
    nav_privacy: "ግላዊነት",
    nav_terms: "ውሎች",
    nav_contact: "አግኙን",
    header_tagline: "በማንኛውም ቋንቋ ድርድር ያድርጉ። ሐረግ ይጫኑ፣ ይቅዱ፣ ስምምነት ይጨርሱ።",
    label_i_speak: "እኔ እናገራለሁ",
    label_they_speak: "እነሱ ይናገራሉ",
    btn_buying: "🛒 እየገዛሁ ነው",
    btn_selling: "💰 እየሸጥኩ ነው",
    cat_opening: "ሰላምታ እና መክፈቻ",
    cat_negotiating: "የዋጋ ድርድር",
    cat_logistics: "ሎጂስቲክስ",
    cat_closing: "ስምምነት መጨረስ",
    cat_listing: "ማስታወቂያ እና ሰላምታ",
    custom_placeholder: "ለመተርጎም የራስዎን ሐረግ ይጻፉ...",
    btn_translate: "ተርጉም →",
    toast_copied: "✅ ተቀድቷል! በውይይትዎ ላይ ይለጥፉ",
    guide_cta: "📖 Facebook Marketplace ላይ እንዴት ድርድር ማድረግ ይቻላል →",
    guide_cta_sub: "ምክሮች፣ ስነ-ምግባር፣ ደህንነት እና የቋንቋ እንቅፋቶችን እንዴት ማሸነፍ ይቻላል",
    footer_copyright: "© 2026 Haggly። ለዓለም አቀፍ ገበያ በ❤️ የተሰራ።",
    footer_about: "ስለ እኛ",
    footer_privacy: "የግላዊነት ፖሊሲ",
    footer_terms: "የአገልግሎት ውሎች",
    footer_contact: "አግኙን",
    custom_no_translation: "ብጁ ትርጉም የኢንተርኔት ግንኙነት ይፈልጋል። በአሁኑ ጊዜ ከላይ ያሉትን ቀድሞ የተዘጋጁ ሐረጎች ይጠቀሙ!",
    page_about_title: "ስለ Haggly",
    page_about_subtitle: "በአካባቢ ንግድ ውስጥ የቋንቋ መሰናክሎችን ማፍረስ",
    page_guide_title: "Facebook Marketplace ላይ እንዴት ድርድር ማድረግ ይቻላል",
    page_guide_subtitle: "ለተሻሉ ስምምነቶች እና በቋንቋዎች ለመግባባት ሙሉ መመሪያ",
    page_privacy_title: "የግላዊነት ፖሊሲ",
    page_privacy_subtitle: "የመጨረሻ ዝማኔ: ፌብሩዋሪ 14, 2026",
    page_terms_title: "የአገልግሎት ውሎች",
    page_terms_subtitle: "የመጨረሻ ዝማኔ: ፌብሩዋሪ 14, 2026",
    page_contact_title: "አግኙን",
    page_contact_subtitle: "ጥያቄዎች፣ አስተያየቶች ወይም የትርጉም ጥቆማዎች? ከእርስዎ መስማት እንወዳለን።",
    swap_title: "ቋንቋዎችን ቀያይር",
    negotiation_tool: "💬 የድርድር ሐረግ ማመንጫ",
    nego_asking_price: "የተጠየቀ ዋጋ",
    nego_target_price: "የእርስዎ ዒላማ ዋጋ",
    nego_walkaway_price: "ዝቅተኛ ዋጋ",
    nego_generate: "ሐረጎችን ፍጠር ✨",
    nego_tone_friendly: "ወዳጃዊ",
    nego_tone_savvy: "ብልህ",
    nego_tone_walkaway: "መሄድ"
  },
  ht: {
    nav_home: "Akèy",
    nav_guide: "Gid Vil",
    nav_about: "Konsènan",
    nav_privacy: "Konfidansyalite",
    nav_terms: "Kondisyon",
    nav_contact: "Kontak",
    header_tagline: "Negosye nan nenpòt lang. Tape yon fraz, kopye li, fèmen dil la.",
    label_i_speak: "Mwen pale",
    label_they_speak: "Yo pale",
    btn_buying: "🛒 M ap achte",
    btn_selling: "💰 M ap vann",
    cat_opening: "Salitasyon ak ouvèti",
    cat_negotiating: "Negosyasyon pri",
    cat_logistics: "Lojistik",
    cat_closing: "Fèmen dil la",
    cat_listing: "Lis ak salitasyon",
    custom_placeholder: "Tape pwòp fraz ou pou tradui...",
    btn_translate: "Tradui →",
    toast_copied: "✅ Kopye! Kole li nan chat ou",
    guide_cta: "📖 Kijan pou negosye sou Facebook Marketplace →",
    guide_cta_sub: "Konsèy, etiket, sekirite ak kijan pou jere baryè lang",
    footer_copyright: "© 2026 Haggly. Bati avèk ❤️ pou mache mondyal la.",
    footer_about: "Konsènan",
    footer_privacy: "Politik Konfidansyalite",
    footer_terms: "Kondisyon Sèvis",
    footer_contact: "Kontak",
    custom_no_translation: "Tradiksyon pèsonalize bezwen koneksyon entènèt. Pou kounye a, sèvi ak fraz ki deja la pi wo a!",
    page_about_title: "Konsènan Haggly",
    page_about_subtitle: "Kraze baryè lang nan komès lokal",
    page_guide_title: "Kijan pou negosye sou Facebook Marketplace",
    page_guide_subtitle: "Gid konplè pou pi bon dil ak kominikasyon ant lang",
    page_privacy_title: "Politik Konfidansyalite",
    page_privacy_subtitle: "Dènye mizajou: 14 fevriye 2026",
    page_terms_title: "Kondisyon Sèvis",
    page_terms_subtitle: "Dènye mizajou: 14 fevriye 2026",
    page_contact_title: "Kontakte Nou",
    page_contact_subtitle: "Kesyon, fidbak oswa sijesyon tradiksyon? Nou ta renmen tande ou.",
    swap_title: "Chanje lang",
    negotiation_tool: "💬 Jeneratè Negosyasyon",
    nego_asking_price: "Pri yo mande",
    nego_target_price: "Pri ou vize",
    nego_walkaway_price: "Pi ba pri ou",
    nego_generate: "Jenere fraz yo ✨",
    nego_tone_friendly: "Zanmi",
    nego_tone_savvy: "Entèlijan",
    nego_tone_walkaway: "Ale"
  },
  th: {
    nav_home: "หน้าแรก",
    nav_guide: "คู่มือเมือง",
    nav_about: "เกี่ยวกับ",
    nav_privacy: "ความเป็นส่วนตัว",
    nav_terms: "ข้อกำหนด",
    nav_contact: "ติดต่อ",
    header_tagline: "ต่อรองราคาได้ทุกภาษา แตะวลี คัดลอก ปิดดีล",
    label_i_speak: "ฉันพูด",
    label_they_speak: "เขาพูด",
    btn_buying: "🛒 ฉันจะซื้อ",
    btn_selling: "💰 ฉันจะขาย",
    cat_opening: "ทักทายและเปิดเรื่อง",
    cat_negotiating: "ต่อรองราคา",
    cat_logistics: "นัดรับสินค้า",
    cat_closing: "ปิดดีล",
    cat_listing: "ลงประกาศและทักทาย",
    custom_placeholder: "พิมพ์ประโยคที่ต้องการแปล...",
    btn_translate: "แปล →",
    toast_copied: "✅ คัดลอกแล้ว! วางในแชทได้เลย",
    guide_cta: "📖 วิธีต่อรองราคาบน Facebook Marketplace →",
    guide_cta_sub: "เคล็ดลับ มารยาท ความปลอดภัย และวิธีรับมือกับอุปสรรคด้านภาษา",
    footer_copyright: "© 2026 Haggly สร้างด้วย ❤️ เพื่อตลาดทั่วโลก",
    footer_about: "เกี่ยวกับ",
    footer_privacy: "นโยบายความเป็นส่วนตัว",
    footer_terms: "ข้อกำหนดการใช้งาน",
    footer_contact: "ติดต่อเรา",
    custom_no_translation: "การแปลเองต้องมีอินเทอร์เน็ต ตอนนี้ใช้วลีสำเร็จรูปด้านบนก่อนนะครับ/คะ!",
    page_about_title: "เกี่ยวกับ Haggly",
    page_about_subtitle: "ทลายกำแพงภาษาในการซื้อขายท้องถิ่น",
    page_guide_title: "วิธีต่อรองราคาบน Facebook Marketplace",
    page_guide_subtitle: "คู่มือฉบับเต็มสำหรับดีลที่ดีกว่าและการสื่อสารข้ามภาษา",
    page_privacy_title: "นโยบายความเป็นส่วนตัว",
    page_privacy_subtitle: "อัปเดตล่าสุด: 14 กุมภาพันธ์ 2026",
    page_terms_title: "ข้อกำหนดการใช้งาน",
    page_terms_subtitle: "อัปเดตล่าสุด: 14 กุมภาพันธ์ 2026",
    page_contact_title: "ติดต่อเรา",
    page_contact_subtitle: "มีคำถาม ข้อเสนอแนะ หรือคำแนะนำการแปล? เรายินดีรับฟังครับ/ค่ะ",
    swap_title: "สลับภาษา",
    negotiation_tool: "💬 ตัวสร้างประโยคต่อรอง",
    nego_asking_price: "ราคาที่ขอ",
    nego_target_price: "ราคาเป้าหมาย",
    nego_walkaway_price: "ราคาต่ำสุด",
    nego_generate: "สร้างประโยค ✨",
    nego_tone_friendly: "เป็นมิตร",
    nego_tone_savvy: "ชาญฉลาด",
    nego_tone_walkaway: "เดินจากไป"
  },
  tr: {
    nav_home: "Ana Sayfa",
    nav_guide: "Şehir Rehberleri",
    nav_about: "Hakkında",
    nav_privacy: "Gizlilik",
    nav_terms: "Şartlar",
    nav_contact: "İletişim",
    header_tagline: "Herhangi bir dilde pazarlık yap. Cümleye dokun, kopyala, anlaşmayı kapat.",
    label_i_speak: "Ben konuşuyorum",
    label_they_speak: "Onlar konuşuyor",
    btn_buying: "🛒 Satın alıyorum",
    btn_selling: "💰 Satıyorum",
    cat_opening: "Karşılama ve açılış",
    cat_negotiating: "Fiyat pazarlığı",
    cat_logistics: "Lojistik",
    cat_closing: "Anlaşmayı kapatma",
    cat_listing: "İlan ve karşılama",
    custom_placeholder: "Çevirmek istediğin cümleyi yaz...",
    btn_translate: "Çevir →",
    toast_copied: "✅ Kopyalandı! Sohbetine yapıştır",
    guide_cta: "📖 Facebook Marketplace'te Nasıl Pazarlık Yapılır →",
    guide_cta_sub: "İpuçları, görgü kuralları, güvenlik ve dil engellerini aşma yolları",
    footer_copyright: "© 2026 Haggly. Küresel pazar için ❤️ ile yapıldı.",
    footer_about: "Hakkında",
    footer_privacy: "Gizlilik Politikası",
    footer_terms: "Kullanım Şartları",
    footer_contact: "İletişim",
    custom_no_translation: "Özel çeviri internet bağlantısı gerektirir. Şimdilik yukarıdaki hazır cümleleri kullan!",
    page_about_title: "Haggly Hakkında",
    page_about_subtitle: "Yerel ticarette dil engellerini yıkmak",
    page_guide_title: "Facebook Marketplace'te Nasıl Pazarlık Yapılır",
    page_guide_subtitle: "Daha iyi fırsatlar ve diller arası iletişim için eksiksiz rehber",
    page_privacy_title: "Gizlilik Politikası",
    page_privacy_subtitle: "Son güncelleme: 14 Şubat 2026",
    page_terms_title: "Kullanım Şartları",
    page_terms_subtitle: "Son güncelleme: 14 Şubat 2026",
    page_contact_title: "Bize Ulaşın",
    page_contact_subtitle: "Soru, geri bildirim veya çeviri önerisi mi var? Seni duymak isteriz.",
    swap_title: "Dilleri değiştir",
    negotiation_tool: "💬 Pazarlık Üreteci",
    nego_asking_price: "İstenen fiyat",
    nego_target_price: "Hedef fiyatınız",
    nego_walkaway_price: "En düşük fiyatınız",
    nego_generate: "Cümleler oluştur ✨",
    nego_tone_friendly: "Dostça",
    nego_tone_savvy: "Akıllıca",
    nego_tone_walkaway: "Çekilme"
  },
  id: {
    nav_home: "Beranda",
    nav_guide: "Panduan Kota",
    nav_about: "Tentang",
    nav_privacy: "Privasi",
    nav_terms: "Ketentuan",
    nav_contact: "Kontak",
    header_tagline: "Negosiasi dalam bahasa apa pun. Ketuk frasa, salin, tutup transaksi.",
    label_i_speak: "Saya bicara",
    label_they_speak: "Mereka bicara",
    btn_buying: "🛒 Saya membeli",
    btn_selling: "💰 Saya menjual",
    cat_opening: "Salam dan pembuka",
    cat_negotiating: "Negosiasi harga",
    cat_logistics: "Logistik",
    cat_closing: "Menutup transaksi",
    cat_listing: "Iklan dan salam",
    custom_placeholder: "Ketik frasa kamu untuk diterjemahkan...",
    btn_translate: "Terjemahkan →",
    toast_copied: "✅ Disalin! Tempel di chat kamu",
    guide_cta: "📖 Cara Negosiasi di Facebook Marketplace →",
    guide_cta_sub: "Tips, etika, keamanan, dan cara mengatasi kendala bahasa",
    footer_copyright: "© 2026 Haggly. Dibuat dengan ❤️ untuk pasar global.",
    footer_about: "Tentang",
    footer_privacy: "Kebijakan Privasi",
    footer_terms: "Ketentuan Layanan",
    footer_contact: "Kontak",
    custom_no_translation: "Terjemahan kustom butuh koneksi internet. Untuk sementara, gunakan frasa yang sudah tersedia di atas!",
    page_about_title: "Tentang Haggly",
    page_about_subtitle: "Meruntuhkan hambatan bahasa dalam perdagangan lokal",
    page_guide_title: "Cara Negosiasi di Facebook Marketplace",
    page_guide_subtitle: "Panduan lengkap untuk transaksi lebih baik dan komunikasi lintas bahasa",
    page_privacy_title: "Kebijakan Privasi",
    page_privacy_subtitle: "Terakhir diperbarui: 14 Februari 2026",
    page_terms_title: "Ketentuan Layanan",
    page_terms_subtitle: "Terakhir diperbarui: 14 Februari 2026",
    page_contact_title: "Hubungi Kami",
    page_contact_subtitle: "Ada pertanyaan, masukan, atau saran terjemahan? Kami senang mendengar dari kamu.",
    swap_title: "Tukar bahasa",
    negotiation_tool: "💬 Generator Negosiasi",
    nego_asking_price: "Harga yang diminta",
    nego_target_price: "Harga target Anda",
    nego_walkaway_price: "Harga terendah Anda",
    nego_generate: "Buat frasa ✨",
    nego_tone_friendly: "Ramah",
    nego_tone_savvy: "Cerdas",
    nego_tone_walkaway: "Pergi"
  }
};

// Language metadata for pickers
const LANGUAGES = [
  { code: 'en', flag: '🇺🇸', name: 'English', native: 'English' },
  { code: 'es', flag: '🇪🇸', name: 'Spanish', native: 'Español' },
  { code: 'zh', flag: '🇨🇳', name: 'Chinese', native: '中文' },
  { code: 'ar', flag: '🇸🇦', name: 'Arabic', native: 'العربية' },
  { code: 'hi', flag: '🇮🇳', name: 'Hindi', native: 'हिन्दी' },
  { code: 'pt', flag: '🇧🇷', name: 'Portuguese', native: 'Português' },
  { code: 'fr', flag: '🇫🇷', name: 'French', native: 'Français' },
  { code: 'de', flag: '🇩🇪', name: 'German', native: 'Deutsch' },
  { code: 'ja', flag: '🇯🇵', name: 'Japanese', native: '日本語' },
  { code: 'ko', flag: '🇰🇷', name: 'Korean', native: '한국어' },
  { code: 'vi', flag: '🇻🇳', name: 'Vietnamese', native: 'Tiếng Việt' },
  { code: 'tl', flag: '🇵🇭', name: 'Tagalog', native: 'Tagalog' },
  { code: 'ru', flag: '🇷🇺', name: 'Russian', native: 'Русский' },
  { code: 'pl', flag: '🇵🇱', name: 'Polish', native: 'Polski' },
  { code: 'uk', flag: '🇺🇦', name: 'Ukrainian', native: 'Українська' },
  { code: 'sw', flag: '🇰🇪', name: 'Swahili', native: 'Kiswahili' },
  { code: 'ha', flag: '🇳🇬', name: 'Hausa', native: 'Hausa' },
  { code: 'am', flag: '🇪🇹', name: 'Amharic', native: 'አማርኛ' },
  { code: 'ht', flag: '🇭🇹', name: 'Haitian Creole', native: 'Kreyòl Ayisyen' },
  { code: 'th', flag: '🇹🇭', name: 'Thai', native: 'ไทย' },
  { code: 'tr', flag: '🇹🇷', name: 'Turkish', native: 'Türkçe' },
  { code: 'id', flag: '🇮🇩', name: 'Indonesian', native: 'Bahasa Indonesia' }
];

// BCP 47 language tag mapping for TTS
const BCP47_MAP = {
  en: 'en-US', es: 'es-ES', zh: 'zh-CN', ar: 'ar-SA', hi: 'hi-IN',
  pt: 'pt-BR', fr: 'fr-FR', de: 'de-DE', ja: 'ja-JP', ko: 'ko-KR',
  vi: 'vi-VN', tl: 'fil-PH', ru: 'ru-RU', pl: 'pl-PL', uk: 'uk-UA',
  sw: 'sw-KE', ha: 'ha-NG', am: 'am-ET', ht: 'ht-HT',
  th: 'th-TH', tr: 'tr-TR', id: 'id-ID'
};

// Category name mapping (English key → UI_STRINGS key)
const CATEGORY_KEY_MAP = {
  "Opening & Greeting": "cat_opening",
  "Negotiating Price": "cat_negotiating",
  "Logistics": "cat_logistics",
  "Closing the Deal": "cat_closing",
  "Listing & Greeting": "cat_listing"
};
